# Site settings
title: picnic
description: a simple picnic planner
baseurl: /picnic # the subpath of your site, e.g. /blog/
url: "http://timmliu.github.io" # the base hostname & protocol for your site
twitter_username: timmliu
github_username:  timmliu
host: localhost

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, README.md, feed.xml]
